---

- hosts:
  - aws

  vars:
    message: "Welcome to my web server"
    ports:
      - http
      - ssh

  tasks:

  - name: Set fact to node2
    set_fact: 
      message: "Hello from {{ ansible_facts[\"fqdn\"] }}"
    when: inventory_hostname == "node2.example.com"

  - name: Become block
    block:

      - name: Ensure apache is present
        yum:
          name: "{{ item }}"
          state: present
        loop:
          - epel-release
          - httpd
          - firewalld

      - name: Ensure {{ name }} started
        systemd:
          name: "{{ name }}"
          state: started
        vars:
          name: firewalld

      - name: Find errors
        block:  

          - name: Ensure {{ name }} started
            systemd:
              name: "{{ name }}"
              state: started
            vars:
              name: httpd
            register: result
            tags: test
    
          - name: State of apache
            debug:
              msg: "Apache has state {{ result.state }}"
            when: result.state == "started"
            tags: test

        rescue:
          - name: Fail of start
            debug:
              msg: "Apache hasn't state started"
            tags: test

      - name: Permit traffic in default zone for http service
        firewalld:
          service: "{{ item }}"
          permanent: yes
          state: enabled
        loop: "{{ ports }}"
        notify:
        - Reload firewalld

      - name: Add my site
        file:
          path: /var/www/html/index.html
          state: touch
          mode: u+rw,g+rw,o-rwx
          owner: root
          group: apache
        when: inventory_hostname != "node1.example.com"
        notify:
        - Reload apache

      - name: Add content
        lineinfile:
          path: /var/www/html/index.html
          line: "{{ message }}"
          create: yes
        when: inventory_hostname != "node1.example.com"
        notify:
        - Reload apache

      - name: Use template for node1
        template:
          src: templates/index.html.j2
          dest: /var/www/html/index.html
          owner: root
          group: apache
          mode: '0640'
        when: inventory_hostname == "node1.example.com"

    become_user: root
    become: yes
    when: ansible_facts['distribution'] == 'CentOS'
    
  handlers:

    - name: Reload firewalld
      systemd:
        state: reloaded
        name: firewalld
      become: yes

    - name: Reload apache
      systemd:
        state: reloaded
        name: httpd
      become: yes
