"aws":
  "hosts":
    "control.example.com":
      "ansible_host": "3.64.56.185"
      "ansible_port": "22"
      "ansible_user": "centos"
    "node1.example.com":
      "ansible_host": "54.93.76.40"
      "ansible_port": "22"
      "ansible_user": "centos"
    "node2.example.com":
      "ansible_host": "18.185.80.84"
      "ansible_port": "22"
      "ansible_user": "centos"
  "vars":
    "ansible_ssh_common_args": "-o StrictHostKeyChecking=no"

